### ISSUE TITLE
Report sentence to improve heuristics: 'I missed updating this test' flagged as negative

### ISSUE THREAD

**Issue by elinor-fung** [jonathanpeppers/inclusive-code-comments#116]
The following word or sentence is acceptable:

     I missed updating this test

Additional info:

* Description: This phrase could be considered negative. Would you like to rephrase?
* Context phrase: ... in some cases.| I missed updating this test|.
* isPartialValidation: false
* isPicky: false
* isPunctuationError: false
* isSpellingError: false
* isStyleError: true
* language: en-US (English (US))

**Comment by rachelkang** [comment]
Thanks for sharing! We're adding these examples to our sentiment analysis model.
