### ISSUE TITLE
Report sentence to improve heuristics: common terms related to software issues

### ISSUE THREAD

**Issue by elinor-fung** [jonathanpeppers/inclusive-code-comments#117]
The following word or sentence is acceptable:

    This was an access violation.

Additional info:

* Description: This phrase could be considered negative. Would you like to rephrase?
* Context phrase: |This was an access violation.|
* isPartialValidation: false
* isPicky: false
* isPunctuationError: false
* isSpellingError: false
* isStyleError: true
* language: en-US (English (US))

Other exmples that were flagged as part of `This was [a/an] ____`:
- aborted thread
- breaking change
- cancelled task
- corrupted memory
- dead code
- fail fast exception
- invalid IL
- stack misalignment
- version mismatch
- weak reference

I guess this may be part of / addressed by the custom model desire? It does mean that basically all my PR descriptions and a lot of my comments are being flagged as negative right now.

**Comment by jonathanpeppers** [comment]
Yes, we just started working on a model last week. These examples above are helpful and we should put these in our training set, thanks!

**Comment by rachelkang** [comment]
Thanks for sharing! As @jonathanpeppers mentioned, we're adding these examples to our sentiment analysis model.
