### ISSUE TITLE
Report sentence to improve heuristics

### ISSUE THREAD

**Issue by Eilon** [jonathanpeppers/inclusive-code-comments#121]
The following word or sentence is acceptable:

    

BTW these are the two bugs that we will try to patch for .NET 6.x that are preventing JS initializers from working in .NET MAUI

Additional info:

* Description: This phrase could be considered negative. Would you like to rephrase?
* Context phrase: ... call succeeds.|

BTW these are the two bugs that we will try to patch for .NET 6.x that are preventing JS initializers from working in .NET MAUI|:

1. https://g...
* isPartialValidation: false
* isPicky: false
* isPunctuationError: false
* isSpellingError: false
* isStyleError: true
* language: en-US (English (US))

**Comment by rachelkang** [comment]
Thanks for sharing! We're adding this example to our sentiment analysis model.
