### ISSUE TITLE
Inconsistency with usage of hacker?

### ISSUE THREAD

**Issue by hartez** [jonathanpeppers/inclusive-code-comments#44]
In suggestions.js, "hacker" is included as a possibly gendered term that may need to be replaced. But earlier in the file the term is suggested as part of the replacement for two other terms.

**Comment by jonathanpeppers** [comment]
Thanks @hartez, nice catch.

https://github.com/jonathanpeppers/inclusive-code-comments/blob/793c22def02cf2448e1153eafcf691ef3e221094/src-packed/suggestions.js#L14-L15

https://github.com/jonathanpeppers/inclusive-code-comments/blob/793c22def02cf2448e1153eafcf691ef3e221094/src-packed/suggestions.js#L40

@rachelkang should they just both suggest "ethical developer", for example?

**Comment by rachelkang** [comment]
Thanks for catching that EZ! and yep, that sounds great to me
