### ISSUE TITLE
Add some kind of ignore list for negative sentiment analysis

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-code-comments#47]
We are finding it difficult to write a code review like:

* "This won't work because XYZ"
* "This failed, the error message is XYZ"

We might want to come up with a list of things to ignore negative sentiment on. It's probably better for this extension to be "less noisy" and potentially miss a few comments in the wild.

**Comment by rolfbjarne** [comment]
Another example:

* "There are test failures"

**Comment by pjcollins** [comment]
This is a tough issue, I've been seeing this in a lot of places. In fact, every sentence in this comment is marked as a negative sentiment.

Here's another example:

 > This would avoid some of the limitations of using the built in Azure Pipelines artifact management for complex release tasks.

Aknowledging that a solution would avoid something problematic is considered negative. I'm finding it hard to think of ways to solve this outside of the suggestion of trying to train the Text Analytics model with more data.

**Comment by pjcollins** [comment]
I like that idea, some UI/UX related change that differentiates the Text Analytics results would I think be a good short term improvement.
