### ISSUE TITLE
Implement telemetry

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-code-comments#5]
We want to track usage of the extension. Events such as:

* Extension was installed - generate a unique (random) ID to track a single user.
* A sentence/word was underlined by the extension.
* The text was improved by the user and the underlined text was fixed.

The code here would go in:

https://github.com/jonathanpeppers/inclusive-code-comments/blob/ce5a0640884cdb1e4f9a2078cf12a998b987b3ab/src/common/tracker.js#L2-L30

**Comment by mnltejaswini** [comment]
Integrate App Insights

**Comment by jonathanpeppers** [comment]
This might be finished after: https://github.com/jonathanpeppers/inclusive-code-comments/commit/e745af40fdd595746d94993a536d5f4db8189e14

We need to test a bit and see if the data is useful enough.
