### ISSUE TITLE
Certain markdown shows a negative sentiment

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-code-comments#62]
I noticed an image tag is negative, lol:

![image](https://user-images.githubusercontent.com/840039/149549741-f15e79cb-eb4d-46b1-8a42-78635f883518.png)

Somewhat related to how we fixed code blocks in 927031af54e9cc17d867363631f42599e83a4111. Maybe we can use the same idea and replace some markdown expressions with spaces?

**Comment by rachelkang** [comment]
I'm seeing [image] gets picked up as 'brief' now, but not negative
I think maybe whatever you wrote on the next line may have made it 'negative'
