### ISSUE TITLE
Add Ability to ignore certain Tabs

### ISSUE THREAD

**Issue by dellis1972** [jonathanpeppers/inclusive-code-comments#64]
Not sure this is even possible.... but with the extension installed we look at everything that is being typed in the brower. 
This includes things like chat rooms. For example I have. WhatsApp web chat client open, and an Element chat client. 
All of this data is currently being sent to the website. I'm not sure we should be. 

Public comments on say github is fun, but private chat data? Probably not.

Not sure how to solve this one though.

**Comment by jonathanpeppers** [comment]
One thing I did was obscure URLs in our telemetry unless they are DevDiv's Azure DevOps instance or Github:

https://github.com/jonathanpeppers/inclusive-code-comments/commit/9ee7a949aec88e93bcef59c38cf2091b416166cc

We also don't collect the actual text. It is sent to Azure Text Analytics, but that's it.

There is also this menu in settings, does it work?

![image](https://user-images.githubusercontent.com/840039/150154613-46b41d04-aae2-464e-88e7-4079df021227.png)

**Comment by dellis1972** [comment]
The setting to disable checking per website works. I'll close this issue.
