### ISSUE TITLE
Github actions builds a .zip inside a .zip

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-code-comments#66]
If you look at artifacts:

![image](https://user-images.githubusercontent.com/840039/150553610-5804b28c-75a8-4462-9f28-be5ee8d398e2.png)

This is an `artifacts.zip` that has a single `release.zip` inside. It would be nice if this was just the `release.zip`.

**Comment by RishiKumarRay** [comment]
Hey, I have solved this 
![Screenshot from 2022-01-22 02-37-17](https://user-images.githubusercontent.com/87641376/150600307-c5f881e8-04ad-455c-a7a9-1eb39e75f090.png)
But one thing I would like to add there is a annoatation warning that says "There are over 10,000 files in this artifact, consider creating an archive before upload to improve the upload performance."
It can be solved too by adding a zip option before uploading artificats if you say I can raise a PR doing both the changes.

**Comment by jonathanpeppers** [comment]
Yeah, our build produces a `release.zip` in the current directory. So if we could somehow just upload that file as-is. A PR would be nice, thanks!

**Comment by jonathanpeppers** [comment]
@RishiKumarRay it looks like you maybe fixed it? https://github.com/RishiKumarRay/inclusive-code-comments/commit/6ad8713fea180e33faae8915f1411579c81dc587

Can you send a PR?

**Comment by jonathanpeppers** [comment]
Oh, I tested it and it is a `release.zip.zip` with a `release.zip` inside. 😞
