### ISSUE TITLE
`/azp run` is too brief

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-code-comments#77]
I don't know, might be worth ignoring some set of commands?

![image](https://user-images.githubusercontent.com/840039/151813800-5460dbbc-0b67-4d9c-8f51-09ee09df2740.png)

**Comment by mattleibow** [comment]
I also just got one with this comment:

```
Another one:

>  I am seeing unmanaged crashes but I think our fix was just in Preview 13.
```

And that was saying the "Another one:" was too brief. Not sure if that is exactly right because it is the start of a list. Maybe I should be more verbose, but the comment before was listing 2 brief comments.
