### ISSUE TITLE
Phrases flagged as negative

### ISSUE THREAD

**Issue by rolfbjarne** [jonathanpeppers/inclusive-code-comments#81]
https://github.com/xamarin/xamarin-macios/pull/14083#issuecomment-1031130252:

"This avoids poor performance of GetHashCode and Equals that are used for the struct using reflection on the first field."

https://github.com/xamarin/xamarin-macios/pull/14018#issue-1121727494:

"Also, contrary to the other default includes, add a condition so files are
only included if we have a resource prefix (typically "Resources"), otherwise
the entire hard drive might be included, and that's not really what we want."

**Comment by mattleibow** [comment]
Another one:

>  I am seeing unmanaged crashes but I think our fix was just in Preview 13.

**Comment by PureWeen** [comment]
"The ListView is displaying incorrectly."

"In order for the the Button to display correctly."

It looks like it's flagging the word "Correct"

**Comment by mattleibow** [comment]
"Just invoking the Current property causes a crash, so you must be working some magic!"

**Comment by jonathanpeppers** [comment]
> This avoids poor performance of GetHashCode and Equals that are used for the struct using reflection on the first field.

poor -> slow fixes this one

**Comment by jonathanpeppers** [comment]
> Also, contrary to the other default includes, add a condition so files are
only included if we have a resource prefix (typically "Resources"), otherwise
the entire hard drive might be included.

Taking this off: `, and that's not really what we want.`

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/174512617-aa6b955e-cfe0-4872-a58b-e64ff3c3b7a3.png)

![image](https://user-images.githubusercontent.com/4403806/174512696-80566621-4343-4eb3-9db8-97ffae992bff.png)
