### ISSUE TITLE
Gitlab support?

### ISSUE THREAD

**Issue by anaselhajjaji** [jonathanpeppers/inclusive-code-comments#89]
Hello

Nice plugin, does it support Gitlab? if no, any plans to do so?

Thank you!

**Comment by jonathanpeppers** [comment]
It should work in Gitlab, any `<textarea>` should work. If you find it doesn't work, feel free to reopen this, thanks!

We are still somewhat testing out & developing this extension, the build you'll find on Github actions is using a Free-tier Azure service.

If you really wanted to use this, I'd recommend building it from source and creating your own Azure services. That might be more work than what you're after.

If we get this to the point it's on the Chrome web store for everyone, I'll let you know, thanks!
