### ISSUE TITLE
`yield` with backticks considered negative?

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-code-comments#92]
![ff2d6227-1f7f-4362-b687-488a565c3b32](https://user-images.githubusercontent.com/840039/155148416-10c3a8af-a9b8-46af-8762-5ae590fa75aa.jpg)

If you remove the ``` around yield, it becomes positive.

**Comment by tj-devel709** [comment]
I am not sure how to get access to Assign myself here, but I will take a look at this one!
